/******************************************************************************
 * Copyright (C) 2018 by LNLS - Brazilian Synchrotron Light Laboratory
 *
 * Redistribution, modification or use of this software in source or binary
 * forms is permitted as long as the files maintain this copyright. LNLS and
 * the Brazilian Center for Research in Energy and Materials (CNPEM) are not
 * liable for any misuse of this material.
 *
 *****************************************************************************/

/**
 * @file event_manager.h
 * @brief Event manager module
 *
 * This module is responsible for the management of events during power supplies
 * operation, including data log on onboard memory. An event is generated by any
 * of the following situations:
 *
 *      1. Interlocks
 *      2. Alarms, in general caused by unusual operation values
 *      3. Commands received via communication interfaces, such as turn on/off,
 *         selection of operation mode, open/close control loop, changes on
 *         setpoint or other operation paramenters, etc. Usually is done by BSMP
 *         functions or HMI operation.
 *
 * Current version implements only interlocks management, including debouncing
 * logic (on C28).
 *
 * TODO: Events based on alarms and commands, and data log.
 * 
 * @author gabriel.brunheira
 * @date 23/11/2018
 *
 */

#ifndef EVENT_MANAGER_H_
#define EVENT_MANAGER_H_

#include <stdint.h>

extern void set_hard_interlock(uint16_t id, uint32_t itlk);
extern void set_soft_interlock(uint16_t id, uint32_t itlk);

#endif /* EVENT_MANAGER_H_ */
